fix: "Remove" `NavigationRequest<TResult>`
Context: 41103cdf60540ac7130a548bd4f98d4868a3f52c

Fixes: https://github.com/unoplatform/uno.extensions/issues/3022

The problem: Use of `MethodInfo.MakeGenericMethod()` is not Native AOT-
compatible, and attempting to make use of it results in a
`NotSupportedException` at runtime:

	Could not invoke ToRequest<Uno.Extensions.Option`1[[Microsoft.UI.Xaml.Controls.ContentDialogResult, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null]]>(…): 'Uno.Extensions.Navigation.NavigationRequestExtensions.ToRequest[Uno.Extensions.Option`1[Microsoft.UI.Xaml.Controls.ContentDialogResult]](Uno.Extensions.Navigation.RouteHint,Uno.Extensions.Navigation.INavigator,Uno.Extensions.Navigation.IRouteResolver,System.Object,System.Object,System.Threading.CancellationToken)' is missing native code. MethodInfo.MakeGenericMethod() is not compatible with AOT compilation. Inspect and fix AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
	System.NotSupportedException: 'Uno.Extensions.Navigation.NavigationRequestExtensions.ToRequest[Uno.Extensions.Option`1[Microsoft.UI.Xaml.Controls.ContentDialogResult]](Uno.Extensions.Navigation.RouteHint,Uno.Extensions.Navigation.INavigator,Uno.Extensions.Navigation.IRouteResolver,System.Object,System.Object,System.Threading.CancellationToken)' is missing native code. MethodInfo.MakeGenericMethod() is not compatible with AOT compilation. Inspect and fix AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
	   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.GetUncachedMethodInvoker(RuntimeTypeInfo[], MemberInfo) + 0x2a
	   at System.Reflection.Runtime.MethodInfos.RuntimeMethodInfo.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo) + 0x3f
	   at Uno.Extensions.Navigation.NavigationRequestExtensions.InvokeToRequest(RouteHint hint, Type resultType, INavigator navigator, IRouteResolver resolver, Object sender, Object data, CancellationToken cancellation) + 0x241

So what if we just…*didn't* use `NavigationRequest<TResult>`?

~~ Testing ~~

Part of the problem here is verification: there are no *unit tests*
which exercise this code path, and meaningfully adding such tests
would require adding a new `Uno.Extensions.Navigation.UI.Tests`
assembly, and @jonpryor isn't sure what that would look like.

However, there *is* a test, it's just not a *unit* test: the
samples/Playground app.

To manually test, apply this patch:

	diff --git a/samples/Playground/Playground/ViewModels/ShellViewModel.cs b/samples/Playground/Playground/ViewModels/ShellViewModel.cs
	index ac57be5fd..4424fb619 100644
	--- a/samples/Playground/Playground/ViewModels/ShellViewModel.cs
	+++ b/samples/Playground/Playground/ViewModels/ShellViewModel.cs
	@@ -11,6 +11,6 @@ public class ShellViewModel

	 		// Option 2: Only specify the ShellViewModel - this will inject a FrameView and so
	 		// the INavigator corresponds to the Frame (ie no need to nest navigation)
	-		//navigator.NavigateViewAsync<HomePage>(this);
	+		navigator.NavigateViewAsync<HomePage>(this);
	 	}
	 }

(Applying this patch is necessary so that the Playground app will
actually *show a user interface*…)

Build and run, e.g. on/for desktop macOS:

	dotnet build -bl samples/Playground/Playground/Playground.csproj \
	  -f net9.0-desktop -p:TargetFrameworkOverride=net9.0-desktop -p:Build_Desktop=true
	./samples/Playground/Playground/bin/Debug/net9.0-desktop/Playground
	# or `…/Playground | tee o.txt`, to make it easier to search the output

After launching the app:

 1. Click **Code behind samples**
 2. Click **GetDataAsync<TResultData>(…);**
 3. Click **Back with Country**

Then read the app output.  What you *don't* want to see is:

	fail: Playground.Views.CodeBehindPage[0]
	      GetDataAsyncClick: result is null; expected a Country!

You *will* see the above `fail` message, and should expect to see it,
if for step (3) you instead click **Back**, as no `Country` is
returned in that case.

~~ The Fix ~~

The "problem" is in `Navigator.RegionNavigateAsync()`:

	IResponseNavigator? responseNavigator = default;
	if (request.Result is not null)
	{
	  var responseFactory = services.GetRequiredService<IResponseNavigatorFactory>();
	  responseNavigator = request.GetResponseNavigator(responseFactory, this);
	}
	// …
	if (responseNavigator is not null)
	{
	  return responseNavigator.AsResponseWithResult(executedResponse);
	}

In order for methods such as
`NavigatorExtensions.GetDataAsync<TResult>()` to work,
`NavigationRequest.GetResponseNavigator()` must return a non-`null`
value.  Previously, this would only happen if the request was a
`NavigationRequest<TResult>`, and this also shows why
`NavigationRequest<TResult>`,
`NavigationRequestExtensions.ToRequest<TResult>()`, and
`NavigationRequestExtensions.InvokeToRequest()` even existed: so that
that generic method
`IResponseNavigatorFactory.CreateForResultType<TResult>()` could be
executed!

However, we don't *actually* need `hint.Result` to be used as part
of the `CreateForResultType<TResult>()` invocation.  Using `object`
works too, *and* works around the Native AOT issue:

	partial record NavigationRequest {
	  internal virtual IResponseNavigator? GetResponseNavigator(IResponseNavigatorFactory responseFactory, INavigator navigator)
	  {
	    if (Result is null) return null;
	    return responseFactory.CreateForResultType<object>(navigator, this);
	  }
	}

This works because `NavigationResultResponse` will "coerce" types,
via `NavigationResultResponse.AsResultResponse<TResult>()` and
`.AsTypedOption<TResult>()`; so long as the runtime type is compatible
with `TResult`, we're all good!